// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.issuing;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class AuthorizationApproveParams extends ApiParamRequest {
  @SerializedName("expand")
  List<String> expand;

  @SerializedName("held_amount")
  Long heldAmount;

  private AuthorizationApproveParams(List<String> expand, Long heldAmount) {
    this.expand = expand;
    this.heldAmount = heldAmount;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.issuing.AuthorizationApproveParams.Builder();
  }

  public static class Builder {
    private List<String> expand;

    private Long heldAmount;

    public AuthorizationApproveParams build() {
      return new AuthorizationApproveParams(expand, heldAmount);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setHeldAmount(Long heldAmount) {
      this.heldAmount = heldAmount;
      return this;
    }
  }
}
