// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.issuing;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class CardPinUpdateParams extends ApiParamRequest {
  @SerializedName("expand")
  List<String> expand;

  @SerializedName("pin")
  String pin;

  @SerializedName("verification")
  Verification verification;

  private CardPinUpdateParams(List<String> expand, String pin, Verification verification) {
    this.expand = expand;
    this.pin = pin;
    this.verification = verification;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.issuing.CardPinUpdateParams.Builder();
  }

  public static class Builder {
    private List<String> expand;

    private String pin;

    private Verification verification;

    public CardPinUpdateParams build() {
      return new CardPinUpdateParams(expand, pin, verification);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setPin(String pin) {
      this.pin = pin;
      return this;
    }

    public Builder setVerification(Verification.Builder verification) {
      this.verification = verification.build();
      return this;
    }
  }

  public static class Verification {
    @SerializedName("id")
    String id;

    @SerializedName("one_time_code")
    String oneTimeCode;

    private Verification(String id, String oneTimeCode) {
      this.id = id;
      this.oneTimeCode = oneTimeCode;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.issuing.CardPinUpdateParams.Verification.Builder();
    }

    public static class Builder {
      private String id;

      private String oneTimeCode;

      public Verification build() {
        return new Verification(id, oneTimeCode);
      }

      public Builder setId(String id) {
        this.id = id;
        return this;
      }

      public Builder setOneTimeCode(String oneTimeCode) {
        this.oneTimeCode = oneTimeCode;
        return this;
      }
    }
  }
}
