// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.issuing;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class CardholderListParams extends ApiParamRequest {
  @SerializedName("created")
  Object created;

  @SerializedName("email")
  String email;

  @SerializedName("ending_before")
  String endingBefore;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("is_default")
  Boolean isDefault;

  @SerializedName("limit")
  Long limit;

  @SerializedName("phone_number")
  String phoneNumber;

  @SerializedName("starting_after")
  String startingAfter;

  @SerializedName("status")
  Status status;

  @SerializedName("type")
  Type type;

  private CardholderListParams(
      Object created,
      String email,
      String endingBefore,
      List<String> expand,
      Boolean isDefault,
      Long limit,
      String phoneNumber,
      String startingAfter,
      Status status,
      Type type) {
    this.created = created;
    this.email = email;
    this.endingBefore = endingBefore;
    this.expand = expand;
    this.isDefault = isDefault;
    this.limit = limit;
    this.phoneNumber = phoneNumber;
    this.startingAfter = startingAfter;
    this.status = status;
    this.type = type;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.issuing.CardholderListParams.Builder();
  }

  public static class Builder {
    private Object created;

    private String email;

    private String endingBefore;

    private List<String> expand;

    private Boolean isDefault;

    private Long limit;

    private String phoneNumber;

    private String startingAfter;

    private Status status;

    private Type type;

    public CardholderListParams build() {
      return new CardholderListParams(
          created,
          email,
          endingBefore,
          expand,
          isDefault,
          limit,
          phoneNumber,
          startingAfter,
          status,
          type);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setCreated(Long created) {
      this.created = created;
      return this;
    }

    public Builder setCreated(Created.Builder created) {
      this.created = created.build();
      return this;
    }

    public Builder setEmail(String email) {
      this.email = email;
      return this;
    }

    public Builder setEndingBefore(String endingBefore) {
      this.endingBefore = endingBefore;
      return this;
    }

    public Builder setIsDefault(Boolean isDefault) {
      this.isDefault = isDefault;
      return this;
    }

    public Builder setLimit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder setPhoneNumber(String phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    public Builder setStartingAfter(String startingAfter) {
      this.startingAfter = startingAfter;
      return this;
    }

    public Builder setStatus(Status status) {
      this.status = status;
      return this;
    }

    public Builder setType(Type type) {
      this.type = type;
      return this;
    }
  }

  public static class Created {
    @SerializedName("gt")
    Long gt;

    @SerializedName("gte")
    Long gte;

    @SerializedName("lt")
    Long lt;

    @SerializedName("lte")
    Long lte;

    private Created(Long gt, Long gte, Long lt, Long lte) {
      this.gt = gt;
      this.gte = gte;
      this.lt = lt;
      this.lte = lte;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.issuing.CardholderListParams.Created.Builder();
    }

    public static class Builder {
      private Long gt;

      private Long gte;

      private Long lt;

      private Long lte;

      public Created build() {
        return new Created(gt, gte, lt, lte);
      }

      public Builder setGt(Long gt) {
        this.gt = gt;
        return this;
      }

      public Builder setGte(Long gte) {
        this.gte = gte;
        return this;
      }

      public Builder setLt(Long lt) {
        this.lt = lt;
        return this;
      }

      public Builder setLte(Long lte) {
        this.lte = lte;
        return this;
      }
    }
  }

  public enum Status {
    @SerializedName("active")
    ACTIVE("active"),

    @SerializedName("blocked")
    BLOCKED("blocked"),

    @SerializedName("inactive")
    INACTIVE("inactive");

    private final String value;

    Status(String value) {
      this.value = value;
    }
  }

  public enum Type {
    @SerializedName("business_entity")
    BUSINESS_ENTITY("business_entity"),

    @SerializedName("individual")
    INDIVIDUAL("individual");

    private final String value;

    Type(String value) {
      this.value = value;
    }
  }
}
