// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.issuing;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class VerificationCreateParams extends ApiParamRequest {
  @SerializedName("card")
  String card;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("scope")
  Scope scope;

  @SerializedName("verification_method")
  VerificationMethod verificationMethod;

  private VerificationCreateParams(
      String card, List<String> expand, Scope scope, VerificationMethod verificationMethod) {
    this.card = card;
    this.expand = expand;
    this.scope = scope;
    this.verificationMethod = verificationMethod;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.issuing.VerificationCreateParams.Builder();
  }

  public static class Builder {
    private String card;

    private List<String> expand;

    private Scope scope;

    private VerificationMethod verificationMethod;

    public VerificationCreateParams build() {
      return new VerificationCreateParams(card, expand, scope, verificationMethod);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setCard(String card) {
      this.card = card;
      return this;
    }

    public Builder setScope(Scope scope) {
      this.scope = scope;
      return this;
    }

    public Builder setVerificationMethod(VerificationMethod verificationMethod) {
      this.verificationMethod = verificationMethod;
      return this;
    }
  }

  public enum Scope {
    @SerializedName("card_pin_retrieve")
    CARD_PIN_RETRIEVE("card_pin_retrieve"),

    @SerializedName("card_pin_update")
    CARD_PIN_UPDATE("card_pin_update");

    private final String value;

    Scope(String value) {
      this.value = value;
    }
  }

  public enum VerificationMethod {
    @SerializedName("email")
    EMAIL("email"),

    @SerializedName("sms")
    SMS("sms");

    private final String value;

    VerificationMethod(String value) {
      this.value = value;
    }
  }
}
