// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class AccountRejectParams extends ApiParamRequest {
  @SerializedName("expand")
  List<String> expand;

  @SerializedName("reason")
  String reason;

  private AccountRejectParams(List<String> expand, String reason) {
    this.expand = expand;
    this.reason = reason;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.AccountRejectParams.Builder();
  }

  public static class Builder {
    private List<String> expand;

    private String reason;

    public AccountRejectParams build() {
      return new AccountRejectParams(expand, reason);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setReason(String reason) {
      this.reason = reason;
      return this;
    }
  }
}
