// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class AccountLinkCreateParams extends ApiParamRequest {
  @SerializedName("account")
  String account;

  @SerializedName("collect")
  Collect collect;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("failure_url")
  String failureUrl;

  @SerializedName("success_url")
  String successUrl;

  @SerializedName("type")
  String type;

  private AccountLinkCreateParams(
      String account,
      Collect collect,
      List<String> expand,
      String failureUrl,
      String successUrl,
      String type) {
    this.account = account;
    this.collect = collect;
    this.expand = expand;
    this.failureUrl = failureUrl;
    this.successUrl = successUrl;
    this.type = type;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.AccountLinkCreateParams.Builder();
  }

  public static class Builder {
    private String account;

    private Collect collect;

    private List<String> expand;

    private String failureUrl;

    private String successUrl;

    private String type;

    public AccountLinkCreateParams build() {
      return new AccountLinkCreateParams(account, collect, expand, failureUrl, successUrl, type);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setAccount(String account) {
      this.account = account;
      return this;
    }

    public Builder setCollect(Collect collect) {
      this.collect = collect;
      return this;
    }

    public Builder setFailureUrl(String failureUrl) {
      this.failureUrl = failureUrl;
      return this;
    }

    public Builder setSuccessUrl(String successUrl) {
      this.successUrl = successUrl;
      return this;
    }

    public Builder setType(String type) {
      this.type = type;
      return this;
    }
  }

  public enum Collect {
    @SerializedName("currently_due")
    CURRENTLY_DUE("currently_due"),

    @SerializedName("eventually_due")
    EVENTUALLY_DUE("eventually_due");

    private final String value;

    Collect(String value) {
      this.value = value;
    }
  }
}
