// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BankAccountUpdateOnAccountParams extends ApiParamRequest {
  @SerializedName("account_holder_name")
  String accountHolderName;

  @SerializedName("account_holder_type")
  AccountHolderType accountHolderType;

  @SerializedName("address_city")
  String addressCity;

  @SerializedName("address_country")
  String addressCountry;

  @SerializedName("address_line1")
  String addressLine1;

  @SerializedName("address_line2")
  String addressLine2;

  @SerializedName("address_state")
  String addressState;

  @SerializedName("address_zip")
  String addressZip;

  @SerializedName("default_for_currency")
  Boolean defaultForCurrency;

  @SerializedName("exp_month")
  String expMonth;

  @SerializedName("exp_year")
  String expYear;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("name")
  String name;

  private BankAccountUpdateOnAccountParams(
      String accountHolderName,
      AccountHolderType accountHolderType,
      String addressCity,
      String addressCountry,
      String addressLine1,
      String addressLine2,
      String addressState,
      String addressZip,
      Boolean defaultForCurrency,
      String expMonth,
      String expYear,
      List<String> expand,
      Map<String, String> metadata,
      String name) {
    this.accountHolderName = accountHolderName;
    this.accountHolderType = accountHolderType;
    this.addressCity = addressCity;
    this.addressCountry = addressCountry;
    this.addressLine1 = addressLine1;
    this.addressLine2 = addressLine2;
    this.addressState = addressState;
    this.addressZip = addressZip;
    this.defaultForCurrency = defaultForCurrency;
    this.expMonth = expMonth;
    this.expYear = expYear;
    this.expand = expand;
    this.metadata = metadata;
    this.name = name;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.BankAccountUpdateOnAccountParams.Builder();
  }

  public static class Builder {
    private String accountHolderName;

    private AccountHolderType accountHolderType;

    private String addressCity;

    private String addressCountry;

    private String addressLine1;

    private String addressLine2;

    private String addressState;

    private String addressZip;

    private Boolean defaultForCurrency;

    private String expMonth;

    private String expYear;

    private List<String> expand;

    private Map<String, String> metadata;

    private String name;

    public BankAccountUpdateOnAccountParams build() {
      return new BankAccountUpdateOnAccountParams(
          accountHolderName,
          accountHolderType,
          addressCity,
          addressCountry,
          addressLine1,
          addressLine2,
          addressState,
          addressZip,
          defaultForCurrency,
          expMonth,
          expYear,
          expand,
          metadata,
          name);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setAccountHolderName(String accountHolderName) {
      this.accountHolderName = accountHolderName;
      return this;
    }

    public Builder setAccountHolderType(AccountHolderType accountHolderType) {
      this.accountHolderType = accountHolderType;
      return this;
    }

    public Builder setAddressCity(String addressCity) {
      this.addressCity = addressCity;
      return this;
    }

    public Builder setAddressCountry(String addressCountry) {
      this.addressCountry = addressCountry;
      return this;
    }

    public Builder setAddressLine1(String addressLine1) {
      this.addressLine1 = addressLine1;
      return this;
    }

    public Builder setAddressLine2(String addressLine2) {
      this.addressLine2 = addressLine2;
      return this;
    }

    public Builder setAddressState(String addressState) {
      this.addressState = addressState;
      return this;
    }

    public Builder setAddressZip(String addressZip) {
      this.addressZip = addressZip;
      return this;
    }

    public Builder setDefaultForCurrency(Boolean defaultForCurrency) {
      this.defaultForCurrency = defaultForCurrency;
      return this;
    }

    public Builder setExpMonth(String expMonth) {
      this.expMonth = expMonth;
      return this;
    }

    public Builder setExpYear(String expYear) {
      this.expYear = expYear;
      return this;
    }

    public Builder setName(String name) {
      this.name = name;
      return this;
    }
  }

  public enum AccountHolderType {
    @SerializedName("company")
    COMPANY("company"),

    @SerializedName("individual")
    INDIVIDUAL("individual");

    private final String value;

    AccountHolderType(String value) {
      this.value = value;
    }
  }
}
