// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class BitcoinReceiverListParams extends ApiParamRequest {
  @SerializedName("active")
  Boolean active;

  @SerializedName("ending_before")
  String endingBefore;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("filled")
  Boolean filled;

  @SerializedName("limit")
  Long limit;

  @SerializedName("starting_after")
  String startingAfter;

  @SerializedName("uncaptured_funds")
  Boolean uncapturedFunds;

  private BitcoinReceiverListParams(
      Boolean active,
      String endingBefore,
      List<String> expand,
      Boolean filled,
      Long limit,
      String startingAfter,
      Boolean uncapturedFunds) {
    this.active = active;
    this.endingBefore = endingBefore;
    this.expand = expand;
    this.filled = filled;
    this.limit = limit;
    this.startingAfter = startingAfter;
    this.uncapturedFunds = uncapturedFunds;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.BitcoinReceiverListParams.Builder();
  }

  public static class Builder {
    private Boolean active;

    private String endingBefore;

    private List<String> expand;

    private Boolean filled;

    private Long limit;

    private String startingAfter;

    private Boolean uncapturedFunds;

    public BitcoinReceiverListParams build() {
      return new BitcoinReceiverListParams(
          active, endingBefore, expand, filled, limit, startingAfter, uncapturedFunds);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setActive(Boolean active) {
      this.active = active;
      return this;
    }

    public Builder setEndingBefore(String endingBefore) {
      this.endingBefore = endingBefore;
      return this;
    }

    public Builder setFilled(Boolean filled) {
      this.filled = filled;
      return this;
    }

    public Builder setLimit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder setStartingAfter(String startingAfter) {
      this.startingAfter = startingAfter;
      return this;
    }

    public Builder setUncapturedFunds(Boolean uncapturedFunds) {
      this.uncapturedFunds = uncapturedFunds;
      return this;
    }
  }
}
