// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class ChargeCaptureParams extends ApiParamRequest {
  @SerializedName("amount")
  Long amount;

  @SerializedName("application_fee")
  Long applicationFee;

  @SerializedName("destination")
  Destination destination;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("receipt_email")
  String receiptEmail;

  @SerializedName("statement_descriptor")
  String statementDescriptor;

  @SerializedName("transfer_group")
  String transferGroup;

  private ChargeCaptureParams(
      Long amount,
      Long applicationFee,
      Destination destination,
      List<String> expand,
      String receiptEmail,
      String statementDescriptor,
      String transferGroup) {
    this.amount = amount;
    this.applicationFee = applicationFee;
    this.destination = destination;
    this.expand = expand;
    this.receiptEmail = receiptEmail;
    this.statementDescriptor = statementDescriptor;
    this.transferGroup = transferGroup;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.ChargeCaptureParams.Builder();
  }

  public static class Builder {
    private Long amount;

    private Long applicationFee;

    private Destination destination;

    private List<String> expand;

    private String receiptEmail;

    private String statementDescriptor;

    private String transferGroup;

    public ChargeCaptureParams build() {
      return new ChargeCaptureParams(
          amount,
          applicationFee,
          destination,
          expand,
          receiptEmail,
          statementDescriptor,
          transferGroup);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setAmount(Long amount) {
      this.amount = amount;
      return this;
    }

    public Builder setApplicationFee(Long applicationFee) {
      this.applicationFee = applicationFee;
      return this;
    }

    public Builder setDestination(Destination.Builder destination) {
      this.destination = destination.build();
      return this;
    }

    public Builder setReceiptEmail(String receiptEmail) {
      this.receiptEmail = receiptEmail;
      return this;
    }

    public Builder setStatementDescriptor(String statementDescriptor) {
      this.statementDescriptor = statementDescriptor;
      return this;
    }

    public Builder setTransferGroup(String transferGroup) {
      this.transferGroup = transferGroup;
      return this;
    }
  }

  public static class Destination {
    @SerializedName("amount")
    Long amount;

    private Destination(Long amount) {
      this.amount = amount;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.ChargeCaptureParams.Destination.Builder();
    }

    public static class Builder {
      private Long amount;

      public Destination build() {
        return new Destination(amount);
      }

      public Builder setAmount(Long amount) {
        this.amount = amount;
        return this;
      }
    }
  }
}
