// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CouponCreateParams extends ApiParamRequest {
  @SerializedName("amount_off")
  Long amountOff;

  @SerializedName("currency")
  String currency;

  @SerializedName("duration")
  Duration duration;

  @SerializedName("duration_in_months")
  Long durationInMonths;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("id")
  String id;

  @SerializedName("max_redemptions")
  Long maxRedemptions;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("name")
  String name;

  @SerializedName("percent_off")
  BigDecimal percentOff;

  @SerializedName("redeem_by")
  Long redeemBy;

  private CouponCreateParams(
      Long amountOff,
      String currency,
      Duration duration,
      Long durationInMonths,
      List<String> expand,
      String id,
      Long maxRedemptions,
      Map<String, String> metadata,
      String name,
      BigDecimal percentOff,
      Long redeemBy) {
    this.amountOff = amountOff;
    this.currency = currency;
    this.duration = duration;
    this.durationInMonths = durationInMonths;
    this.expand = expand;
    this.id = id;
    this.maxRedemptions = maxRedemptions;
    this.metadata = metadata;
    this.name = name;
    this.percentOff = percentOff;
    this.redeemBy = redeemBy;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.CouponCreateParams.Builder();
  }

  public static class Builder {
    private Long amountOff;

    private String currency;

    private Duration duration;

    private Long durationInMonths;

    private List<String> expand;

    private String id;

    private Long maxRedemptions;

    private Map<String, String> metadata;

    private String name;

    private BigDecimal percentOff;

    private Long redeemBy;

    public CouponCreateParams build() {
      return new CouponCreateParams(
          amountOff,
          currency,
          duration,
          durationInMonths,
          expand,
          id,
          maxRedemptions,
          metadata,
          name,
          percentOff,
          redeemBy);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setAmountOff(Long amountOff) {
      this.amountOff = amountOff;
      return this;
    }

    public Builder setCurrency(String currency) {
      this.currency = currency;
      return this;
    }

    public Builder setDuration(Duration duration) {
      this.duration = duration;
      return this;
    }

    public Builder setDurationInMonths(Long durationInMonths) {
      this.durationInMonths = durationInMonths;
      return this;
    }

    public Builder setId(String id) {
      this.id = id;
      return this;
    }

    public Builder setMaxRedemptions(Long maxRedemptions) {
      this.maxRedemptions = maxRedemptions;
      return this;
    }

    public Builder setName(String name) {
      this.name = name;
      return this;
    }

    public Builder setPercentOff(BigDecimal percentOff) {
      this.percentOff = percentOff;
      return this;
    }

    public Builder setRedeemBy(Long redeemBy) {
      this.redeemBy = redeemBy;
      return this;
    }
  }

  public enum Duration {
    @SerializedName("forever")
    FOREVER("forever"),

    @SerializedName("once")
    ONCE("once"),

    @SerializedName("repeating")
    REPEATING("repeating");

    private final String value;

    Duration(String value) {
      this.value = value;
    }
  }
}
