// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FileLinkUpdateParams extends ApiParamRequest {
  @SerializedName("expand")
  List<String> expand;

  @SerializedName("expires_at")
  Object expiresAt;

  @SerializedName("metadata")
  Map<String, String> metadata;

  private FileLinkUpdateParams(
      List<String> expand, Object expiresAt, Map<String, String> metadata) {
    this.expand = expand;
    this.expiresAt = expiresAt;
    this.metadata = metadata;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.FileLinkUpdateParams.Builder();
  }

  public static class Builder {
    private List<String> expand;

    private Object expiresAt;

    private Map<String, String> metadata;

    public FileLinkUpdateParams build() {
      return new FileLinkUpdateParams(expand, expiresAt, metadata);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setExpiresAt(Long expiresAt) {
      this.expiresAt = expiresAt;
      return this;
    }

    public Builder setExpiresAt(ExpiresAt expiresAt) {
      this.expiresAt = expiresAt;
      return this;
    }
  }

  public enum ExpiresAt {
    @SerializedName("now")
    NOW("now");

    private final String value;

    ExpiresAt(String value) {
      this.value = value;
    }
  }
}
