// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InvoiceCreateParams extends ApiParamRequest {
  @SerializedName("application_fee_amount")
  Long applicationFeeAmount;

  @SerializedName("auto_advance")
  Boolean autoAdvance;

  @SerializedName("billing")
  Billing billing;

  @SerializedName("custom_fields")
  List<CustomFields> customFields;

  @SerializedName("customer")
  String customer;

  @SerializedName("days_until_due")
  Long daysUntilDue;

  @SerializedName("default_source")
  String defaultSource;

  @SerializedName("description")
  String description;

  @SerializedName("due_date")
  Long dueDate;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("footer")
  String footer;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("statement_descriptor")
  String statementDescriptor;

  @SerializedName("subscription")
  String subscription;

  @SerializedName("tax_percent")
  BigDecimal taxPercent;

  private InvoiceCreateParams(
      Long applicationFeeAmount,
      Boolean autoAdvance,
      Billing billing,
      List<CustomFields> customFields,
      String customer,
      Long daysUntilDue,
      String defaultSource,
      String description,
      Long dueDate,
      List<String> expand,
      String footer,
      Map<String, String> metadata,
      String statementDescriptor,
      String subscription,
      BigDecimal taxPercent) {
    this.applicationFeeAmount = applicationFeeAmount;
    this.autoAdvance = autoAdvance;
    this.billing = billing;
    this.customFields = customFields;
    this.customer = customer;
    this.daysUntilDue = daysUntilDue;
    this.defaultSource = defaultSource;
    this.description = description;
    this.dueDate = dueDate;
    this.expand = expand;
    this.footer = footer;
    this.metadata = metadata;
    this.statementDescriptor = statementDescriptor;
    this.subscription = subscription;
    this.taxPercent = taxPercent;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.InvoiceCreateParams.Builder();
  }

  public static class Builder {
    private Long applicationFeeAmount;

    private Boolean autoAdvance;

    private Billing billing;

    private List<CustomFields> customFields;

    private String customer;

    private Long daysUntilDue;

    private String defaultSource;

    private String description;

    private Long dueDate;

    private List<String> expand;

    private String footer;

    private Map<String, String> metadata;

    private String statementDescriptor;

    private String subscription;

    private BigDecimal taxPercent;

    public InvoiceCreateParams build() {
      return new InvoiceCreateParams(
          applicationFeeAmount,
          autoAdvance,
          billing,
          customFields,
          customer,
          daysUntilDue,
          defaultSource,
          description,
          dueDate,
          expand,
          footer,
          metadata,
          statementDescriptor,
          subscription,
          taxPercent);
    }

    public Builder addCustomFields(CustomFields.Builder element) {
      if (this.customFields == null) {
        this.customFields = new ArrayList<>();
      }
      this.customFields.add(element.build());
      return this;
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setApplicationFeeAmount(Long applicationFeeAmount) {
      this.applicationFeeAmount = applicationFeeAmount;
      return this;
    }

    public Builder setAutoAdvance(Boolean autoAdvance) {
      this.autoAdvance = autoAdvance;
      return this;
    }

    public Builder setBilling(Billing billing) {
      this.billing = billing;
      return this;
    }

    public Builder setCustomer(String customer) {
      this.customer = customer;
      return this;
    }

    public Builder setDaysUntilDue(Long daysUntilDue) {
      this.daysUntilDue = daysUntilDue;
      return this;
    }

    public Builder setDefaultSource(String defaultSource) {
      this.defaultSource = defaultSource;
      return this;
    }

    public Builder setDescription(String description) {
      this.description = description;
      return this;
    }

    public Builder setDueDate(Long dueDate) {
      this.dueDate = dueDate;
      return this;
    }

    public Builder setFooter(String footer) {
      this.footer = footer;
      return this;
    }

    public Builder setStatementDescriptor(String statementDescriptor) {
      this.statementDescriptor = statementDescriptor;
      return this;
    }

    public Builder setSubscription(String subscription) {
      this.subscription = subscription;
      return this;
    }

    public Builder setTaxPercent(BigDecimal taxPercent) {
      this.taxPercent = taxPercent;
      return this;
    }
  }

  public static class CustomFields {
    @SerializedName("name")
    String name;

    @SerializedName("value")
    String value;

    private CustomFields(String name, String value) {
      this.name = name;
      this.value = value;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.InvoiceCreateParams.CustomFields.Builder();
    }

    public static class Builder {
      private String name;

      private String value;

      public CustomFields build() {
        return new CustomFields(name, value);
      }

      public Builder setName(String name) {
        this.name = name;
        return this;
      }

      public Builder setValue(String value) {
        this.value = value;
        return this;
      }
    }
  }

  public enum Billing {
    @SerializedName("charge_automatically")
    CHARGE_AUTOMATICALLY("charge_automatically"),

    @SerializedName("send_invoice")
    SEND_INVOICE("send_invoice");

    private final String value;

    Billing(String value) {
      this.value = value;
    }
  }
}
