// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class InvoiceFinalizeInvoiceParams extends ApiParamRequest {
  @SerializedName("auto_advance")
  Boolean autoAdvance;

  @SerializedName("expand")
  List<String> expand;

  private InvoiceFinalizeInvoiceParams(Boolean autoAdvance, List<String> expand) {
    this.autoAdvance = autoAdvance;
    this.expand = expand;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.InvoiceFinalizeInvoiceParams.Builder();
  }

  public static class Builder {
    private Boolean autoAdvance;

    private List<String> expand;

    public InvoiceFinalizeInvoiceParams build() {
      return new InvoiceFinalizeInvoiceParams(autoAdvance, expand);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setAutoAdvance(Boolean autoAdvance) {
      this.autoAdvance = autoAdvance;
      return this;
    }
  }
}
