// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InvoiceItemUpdateParams extends ApiParamRequest {
  @SerializedName("amount")
  Long amount;

  @SerializedName("description")
  String description;

  @SerializedName("discountable")
  Boolean discountable;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("period")
  Period period;

  @SerializedName("quantity")
  Long quantity;

  @SerializedName("unit_amount")
  Long unitAmount;

  private InvoiceItemUpdateParams(
      Long amount,
      String description,
      Boolean discountable,
      List<String> expand,
      Map<String, String> metadata,
      Period period,
      Long quantity,
      Long unitAmount) {
    this.amount = amount;
    this.description = description;
    this.discountable = discountable;
    this.expand = expand;
    this.metadata = metadata;
    this.period = period;
    this.quantity = quantity;
    this.unitAmount = unitAmount;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.InvoiceItemUpdateParams.Builder();
  }

  public static class Builder {
    private Long amount;

    private String description;

    private Boolean discountable;

    private List<String> expand;

    private Map<String, String> metadata;

    private Period period;

    private Long quantity;

    private Long unitAmount;

    public InvoiceItemUpdateParams build() {
      return new InvoiceItemUpdateParams(
          amount, description, discountable, expand, metadata, period, quantity, unitAmount);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setAmount(Long amount) {
      this.amount = amount;
      return this;
    }

    public Builder setDescription(String description) {
      this.description = description;
      return this;
    }

    public Builder setDiscountable(Boolean discountable) {
      this.discountable = discountable;
      return this;
    }

    public Builder setPeriod(Period.Builder period) {
      this.period = period.build();
      return this;
    }

    public Builder setQuantity(Long quantity) {
      this.quantity = quantity;
      return this;
    }

    public Builder setUnitAmount(Long unitAmount) {
      this.unitAmount = unitAmount;
      return this;
    }
  }

  public static class Period {
    @SerializedName("end")
    Long end;

    @SerializedName("start")
    Long start;

    private Period(Long end, Long start) {
      this.end = end;
      this.start = start;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.InvoiceItemUpdateParams.Period.Builder();
    }

    public static class Builder {
      private Long end;

      private Long start;

      public Period build() {
        return new Period(end, start);
      }

      public Builder setEnd(Long end) {
        this.end = end;
        return this;
      }

      public Builder setStart(Long start) {
        this.start = start;
        return this;
      }
    }
  }
}
