// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class PaymentSourceCollectionListParams extends ApiParamRequest {
  @SerializedName("ending_before")
  String endingBefore;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("limit")
  Long limit;

  @SerializedName("object")
  String object;

  @SerializedName("starting_after")
  String startingAfter;

  @SerializedName("type")
  String type;

  private PaymentSourceCollectionListParams(
      String endingBefore,
      List<String> expand,
      Long limit,
      String object,
      String startingAfter,
      String type) {
    this.endingBefore = endingBefore;
    this.expand = expand;
    this.limit = limit;
    this.object = object;
    this.startingAfter = startingAfter;
    this.type = type;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.PaymentSourceCollectionListParams.Builder();
  }

  public static class Builder {
    private String endingBefore;

    private List<String> expand;

    private Long limit;

    private String object;

    private String startingAfter;

    private String type;

    public PaymentSourceCollectionListParams build() {
      return new PaymentSourceCollectionListParams(
          endingBefore, expand, limit, object, startingAfter, type);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setEndingBefore(String endingBefore) {
      this.endingBefore = endingBefore;
      return this;
    }

    public Builder setLimit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder setObject(String object) {
      this.object = object;
      return this;
    }

    public Builder setStartingAfter(String startingAfter) {
      this.startingAfter = startingAfter;
      return this;
    }

    public Builder setType(String type) {
      this.type = type;
      return this;
    }
  }
}
