// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PaymentSourceCollectionCreateParams extends ApiParamRequest {
  @SerializedName("alipay_account")
  Object alipayAccount;

  @SerializedName("bank_account")
  Object bankAccount;

  @SerializedName("card")
  Object card;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("source")
  Object source;

  private PaymentSourceCollectionCreateParams(
      Object alipayAccount,
      Object bankAccount,
      Object card,
      List<String> expand,
      Map<String, String> metadata,
      Object source) {
    this.alipayAccount = alipayAccount;
    this.bankAccount = bankAccount;
    this.card = card;
    this.expand = expand;
    this.metadata = metadata;
    this.source = source;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.PaymentSourceCollectionCreateParams.Builder();
  }

  public static class Builder {
    private Object alipayAccount;

    private Object bankAccount;

    private Object card;

    private List<String> expand;

    private Map<String, String> metadata;

    private Object source;

    public PaymentSourceCollectionCreateParams build() {
      return new PaymentSourceCollectionCreateParams(
          alipayAccount, bankAccount, card, expand, metadata, source);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setAlipayAccount(Map<String, Object> alipayAccount) {
      this.alipayAccount = alipayAccount;
      return this;
    }

    public Builder setAlipayAccount(String alipayAccount) {
      this.alipayAccount = alipayAccount;
      return this;
    }

    public Builder setBankAccount(Map<String, Object> bankAccount) {
      this.bankAccount = bankAccount;
      return this;
    }

    public Builder setBankAccount(String bankAccount) {
      this.bankAccount = bankAccount;
      return this;
    }

    public Builder setCard(Map<String, Object> card) {
      this.card = card;
      return this;
    }

    public Builder setCard(String card) {
      this.card = card;
      return this;
    }

    public Builder setSource(Map<String, Object> source) {
      this.source = source;
      return this;
    }

    public Builder setSource(String source) {
      this.source = source;
      return this;
    }
  }
}
