// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PersonUpdateParams extends ApiParamRequest {
  @SerializedName("address")
  Address address;

  @SerializedName("address_kana")
  AddressKana addressKana;

  @SerializedName("address_kanji")
  AddressKanji addressKanji;

  @SerializedName("dob")
  Dob dob;

  @SerializedName("email")
  String email;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("first_name")
  String firstName;

  @SerializedName("first_name_kana")
  String firstNameKana;

  @SerializedName("first_name_kanji")
  String firstNameKanji;

  @SerializedName("gender")
  String gender;

  @SerializedName("id_number")
  String idNumber;

  @SerializedName("last_name")
  String lastName;

  @SerializedName("last_name_kana")
  String lastNameKana;

  @SerializedName("last_name_kanji")
  String lastNameKanji;

  @SerializedName("maiden_name")
  String maidenName;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("phone")
  String phone;

  @SerializedName("relationship")
  Relationship relationship;

  @SerializedName("ssn_last_4")
  String ssnLast4;

  private PersonUpdateParams(
      Address address,
      AddressKana addressKana,
      AddressKanji addressKanji,
      Dob dob,
      String email,
      List<String> expand,
      String firstName,
      String firstNameKana,
      String firstNameKanji,
      String gender,
      String idNumber,
      String lastName,
      String lastNameKana,
      String lastNameKanji,
      String maidenName,
      Map<String, String> metadata,
      String phone,
      Relationship relationship,
      String ssnLast4) {
    this.address = address;
    this.addressKana = addressKana;
    this.addressKanji = addressKanji;
    this.dob = dob;
    this.email = email;
    this.expand = expand;
    this.firstName = firstName;
    this.firstNameKana = firstNameKana;
    this.firstNameKanji = firstNameKanji;
    this.gender = gender;
    this.idNumber = idNumber;
    this.lastName = lastName;
    this.lastNameKana = lastNameKana;
    this.lastNameKanji = lastNameKanji;
    this.maidenName = maidenName;
    this.metadata = metadata;
    this.phone = phone;
    this.relationship = relationship;
    this.ssnLast4 = ssnLast4;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.PersonUpdateParams.Builder();
  }

  public static class Builder {
    private Address address;

    private AddressKana addressKana;

    private AddressKanji addressKanji;

    private Dob dob;

    private String email;

    private List<String> expand;

    private String firstName;

    private String firstNameKana;

    private String firstNameKanji;

    private String gender;

    private String idNumber;

    private String lastName;

    private String lastNameKana;

    private String lastNameKanji;

    private String maidenName;

    private Map<String, String> metadata;

    private String phone;

    private Relationship relationship;

    private String ssnLast4;

    public PersonUpdateParams build() {
      return new PersonUpdateParams(
          address,
          addressKana,
          addressKanji,
          dob,
          email,
          expand,
          firstName,
          firstNameKana,
          firstNameKanji,
          gender,
          idNumber,
          lastName,
          lastNameKana,
          lastNameKanji,
          maidenName,
          metadata,
          phone,
          relationship,
          ssnLast4);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setAddress(Address.Builder address) {
      this.address = address.build();
      return this;
    }

    public Builder setAddressKana(AddressKana.Builder addressKana) {
      this.addressKana = addressKana.build();
      return this;
    }

    public Builder setAddressKanji(AddressKanji.Builder addressKanji) {
      this.addressKanji = addressKanji.build();
      return this;
    }

    public Builder setDob(Dob.Builder dob) {
      this.dob = dob.build();
      return this;
    }

    public Builder setEmail(String email) {
      this.email = email;
      return this;
    }

    public Builder setFirstName(String firstName) {
      this.firstName = firstName;
      return this;
    }

    public Builder setFirstNameKana(String firstNameKana) {
      this.firstNameKana = firstNameKana;
      return this;
    }

    public Builder setFirstNameKanji(String firstNameKanji) {
      this.firstNameKanji = firstNameKanji;
      return this;
    }

    public Builder setGender(String gender) {
      this.gender = gender;
      return this;
    }

    public Builder setIdNumber(String idNumber) {
      this.idNumber = idNumber;
      return this;
    }

    public Builder setLastName(String lastName) {
      this.lastName = lastName;
      return this;
    }

    public Builder setLastNameKana(String lastNameKana) {
      this.lastNameKana = lastNameKana;
      return this;
    }

    public Builder setLastNameKanji(String lastNameKanji) {
      this.lastNameKanji = lastNameKanji;
      return this;
    }

    public Builder setMaidenName(String maidenName) {
      this.maidenName = maidenName;
      return this;
    }

    public Builder setPhone(String phone) {
      this.phone = phone;
      return this;
    }

    public Builder setRelationship(Relationship.Builder relationship) {
      this.relationship = relationship.build();
      return this;
    }

    public Builder setSsnLast4(String ssnLast4) {
      this.ssnLast4 = ssnLast4;
      return this;
    }
  }

  public static class Address {
    @SerializedName("city")
    String city;

    @SerializedName("country")
    String country;

    @SerializedName("line1")
    String line1;

    @SerializedName("line2")
    String line2;

    @SerializedName("postal_code")
    String postalCode;

    @SerializedName("state")
    String state;

    private Address(
        String city, String country, String line1, String line2, String postalCode, String state) {
      this.city = city;
      this.country = country;
      this.line1 = line1;
      this.line2 = line2;
      this.postalCode = postalCode;
      this.state = state;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.PersonUpdateParams.Address.Builder();
    }

    public static class Builder {
      private String city;

      private String country;

      private String line1;

      private String line2;

      private String postalCode;

      private String state;

      public Address build() {
        return new Address(city, country, line1, line2, postalCode, state);
      }

      public Builder setCity(String city) {
        this.city = city;
        return this;
      }

      public Builder setCountry(String country) {
        this.country = country;
        return this;
      }

      public Builder setLine1(String line1) {
        this.line1 = line1;
        return this;
      }

      public Builder setLine2(String line2) {
        this.line2 = line2;
        return this;
      }

      public Builder setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
      }

      public Builder setState(String state) {
        this.state = state;
        return this;
      }
    }
  }

  public static class AddressKana {
    @SerializedName("city")
    String city;

    @SerializedName("country")
    String country;

    @SerializedName("line1")
    String line1;

    @SerializedName("line2")
    String line2;

    @SerializedName("postal_code")
    String postalCode;

    @SerializedName("state")
    String state;

    @SerializedName("town")
    String town;

    private AddressKana(
        String city,
        String country,
        String line1,
        String line2,
        String postalCode,
        String state,
        String town) {
      this.city = city;
      this.country = country;
      this.line1 = line1;
      this.line2 = line2;
      this.postalCode = postalCode;
      this.state = state;
      this.town = town;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.PersonUpdateParams.AddressKana.Builder();
    }

    public static class Builder {
      private String city;

      private String country;

      private String line1;

      private String line2;

      private String postalCode;

      private String state;

      private String town;

      public AddressKana build() {
        return new AddressKana(city, country, line1, line2, postalCode, state, town);
      }

      public Builder setCity(String city) {
        this.city = city;
        return this;
      }

      public Builder setCountry(String country) {
        this.country = country;
        return this;
      }

      public Builder setLine1(String line1) {
        this.line1 = line1;
        return this;
      }

      public Builder setLine2(String line2) {
        this.line2 = line2;
        return this;
      }

      public Builder setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
      }

      public Builder setState(String state) {
        this.state = state;
        return this;
      }

      public Builder setTown(String town) {
        this.town = town;
        return this;
      }
    }
  }

  public static class AddressKanji {
    @SerializedName("city")
    String city;

    @SerializedName("country")
    String country;

    @SerializedName("line1")
    String line1;

    @SerializedName("line2")
    String line2;

    @SerializedName("postal_code")
    String postalCode;

    @SerializedName("state")
    String state;

    @SerializedName("town")
    String town;

    private AddressKanji(
        String city,
        String country,
        String line1,
        String line2,
        String postalCode,
        String state,
        String town) {
      this.city = city;
      this.country = country;
      this.line1 = line1;
      this.line2 = line2;
      this.postalCode = postalCode;
      this.state = state;
      this.town = town;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.PersonUpdateParams.AddressKanji.Builder();
    }

    public static class Builder {
      private String city;

      private String country;

      private String line1;

      private String line2;

      private String postalCode;

      private String state;

      private String town;

      public AddressKanji build() {
        return new AddressKanji(city, country, line1, line2, postalCode, state, town);
      }

      public Builder setCity(String city) {
        this.city = city;
        return this;
      }

      public Builder setCountry(String country) {
        this.country = country;
        return this;
      }

      public Builder setLine1(String line1) {
        this.line1 = line1;
        return this;
      }

      public Builder setLine2(String line2) {
        this.line2 = line2;
        return this;
      }

      public Builder setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
      }

      public Builder setState(String state) {
        this.state = state;
        return this;
      }

      public Builder setTown(String town) {
        this.town = town;
        return this;
      }
    }
  }

  public static class Dob {
    @SerializedName("day")
    Long day;

    @SerializedName("month")
    Long month;

    @SerializedName("year")
    Long year;

    private Dob(Long day, Long month, Long year) {
      this.day = day;
      this.month = month;
      this.year = year;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.PersonUpdateParams.Dob.Builder();
    }

    public static class Builder {
      private Long day;

      private Long month;

      private Long year;

      public Dob build() {
        return new Dob(day, month, year);
      }

      public Builder setDay(Long day) {
        this.day = day;
        return this;
      }

      public Builder setMonth(Long month) {
        this.month = month;
        return this;
      }

      public Builder setYear(Long year) {
        this.year = year;
        return this;
      }
    }
  }

  public static class Relationship {
    @SerializedName("account_opener")
    Boolean accountOpener;

    @SerializedName("director")
    Boolean director;

    @SerializedName("owner")
    Boolean owner;

    @SerializedName("percent_ownership")
    BigDecimal percentOwnership;

    @SerializedName("title")
    String title;

    private Relationship(
        Boolean accountOpener,
        Boolean director,
        Boolean owner,
        BigDecimal percentOwnership,
        String title) {
      this.accountOpener = accountOpener;
      this.director = director;
      this.owner = owner;
      this.percentOwnership = percentOwnership;
      this.title = title;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.PersonUpdateParams.Relationship.Builder();
    }

    public static class Builder {
      private Boolean accountOpener;

      private Boolean director;

      private Boolean owner;

      private BigDecimal percentOwnership;

      private String title;

      public Relationship build() {
        return new Relationship(accountOpener, director, owner, percentOwnership, title);
      }

      public Builder setAccountOpener(Boolean accountOpener) {
        this.accountOpener = accountOpener;
        return this;
      }

      public Builder setDirector(Boolean director) {
        this.director = director;
        return this;
      }

      public Builder setOwner(Boolean owner) {
        this.owner = owner;
        return this;
      }

      public Builder setPercentOwnership(BigDecimal percentOwnership) {
        this.percentOwnership = percentOwnership;
        return this;
      }

      public Builder setTitle(String title) {
        this.title = title;
        return this;
      }
    }
  }
}
