// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RecipientUpdateParams extends ApiParamRequest {
  @SerializedName("bank_account")
  Object bankAccount;

  @SerializedName("card")
  Object card;

  @SerializedName("default_card")
  String defaultCard;

  @SerializedName("description")
  String description;

  @SerializedName("email")
  String email;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("name")
  String name;

  @SerializedName("tax_id")
  String taxId;

  private RecipientUpdateParams(
      Object bankAccount,
      Object card,
      String defaultCard,
      String description,
      String email,
      List<String> expand,
      Map<String, String> metadata,
      String name,
      String taxId) {
    this.bankAccount = bankAccount;
    this.card = card;
    this.defaultCard = defaultCard;
    this.description = description;
    this.email = email;
    this.expand = expand;
    this.metadata = metadata;
    this.name = name;
    this.taxId = taxId;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.RecipientUpdateParams.Builder();
  }

  public static class Builder {
    private Object bankAccount;

    private Object card;

    private String defaultCard;

    private String description;

    private String email;

    private List<String> expand;

    private Map<String, String> metadata;

    private String name;

    private String taxId;

    public RecipientUpdateParams build() {
      return new RecipientUpdateParams(
          bankAccount, card, defaultCard, description, email, expand, metadata, name, taxId);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setBankAccount(Map<String, Object> bankAccount) {
      this.bankAccount = bankAccount;
      return this;
    }

    public Builder setBankAccount(String bankAccount) {
      this.bankAccount = bankAccount;
      return this;
    }

    public Builder setCard(Map<String, Object> card) {
      this.card = card;
      return this;
    }

    public Builder setCard(String card) {
      this.card = card;
      return this;
    }

    public Builder setDefaultCard(String defaultCard) {
      this.defaultCard = defaultCard;
      return this;
    }

    public Builder setDescription(String description) {
      this.description = description;
      return this;
    }

    public Builder setEmail(String email) {
      this.email = email;
      return this;
    }

    public Builder setName(String name) {
      this.name = name;
      return this;
    }

    public Builder setTaxId(String taxId) {
      this.taxId = taxId;
      return this;
    }
  }
}
