// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SkuUpdateParams extends ApiParamRequest {
  @SerializedName("active")
  Boolean active;

  @SerializedName("attributes")
  Map<String, String> attributes;

  @SerializedName("currency")
  String currency;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("image")
  String image;

  @SerializedName("inventory")
  Inventory inventory;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("package_dimensions")
  PackageDimensions packageDimensions;

  @SerializedName("price")
  Long price;

  @SerializedName("product")
  String product;

  private SkuUpdateParams(
      Boolean active,
      Map<String, String> attributes,
      String currency,
      List<String> expand,
      String image,
      Inventory inventory,
      Map<String, String> metadata,
      PackageDimensions packageDimensions,
      Long price,
      String product) {
    this.active = active;
    this.attributes = attributes;
    this.currency = currency;
    this.expand = expand;
    this.image = image;
    this.inventory = inventory;
    this.metadata = metadata;
    this.packageDimensions = packageDimensions;
    this.price = price;
    this.product = product;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.SkuUpdateParams.Builder();
  }

  public static class Builder {
    private Boolean active;

    private Map<String, String> attributes;

    private String currency;

    private List<String> expand;

    private String image;

    private Inventory inventory;

    private Map<String, String> metadata;

    private PackageDimensions packageDimensions;

    private Long price;

    private String product;

    public SkuUpdateParams build() {
      return new SkuUpdateParams(
          active,
          attributes,
          currency,
          expand,
          image,
          inventory,
          metadata,
          packageDimensions,
          price,
          product);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putAttributes(String key, String value) {
      if (this.attributes == null) {
        this.attributes = new HashMap<>();
      }
      this.attributes.put(key, value);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setActive(Boolean active) {
      this.active = active;
      return this;
    }

    public Builder setCurrency(String currency) {
      this.currency = currency;
      return this;
    }

    public Builder setImage(String image) {
      this.image = image;
      return this;
    }

    public Builder setInventory(Inventory.Builder inventory) {
      this.inventory = inventory.build();
      return this;
    }

    public Builder setPackageDimensions(PackageDimensions.Builder packageDimensions) {
      this.packageDimensions = packageDimensions.build();
      return this;
    }

    public Builder setPrice(Long price) {
      this.price = price;
      return this;
    }

    public Builder setProduct(String product) {
      this.product = product;
      return this;
    }
  }

  public static class Inventory {
    @SerializedName("quantity")
    Long quantity;

    @SerializedName("type")
    Type type;

    @SerializedName("value")
    Value value;

    private Inventory(Long quantity, Type type, Value value) {
      this.quantity = quantity;
      this.type = type;
      this.value = value;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SkuUpdateParams.Inventory.Builder();
    }

    public static class Builder {
      private Long quantity;

      private Type type;

      private Value value;

      public Inventory build() {
        return new Inventory(quantity, type, value);
      }

      public Builder setQuantity(Long quantity) {
        this.quantity = quantity;
        return this;
      }

      public Builder setType(Type type) {
        this.type = type;
        return this;
      }

      public Builder setValue(Value value) {
        this.value = value;
        return this;
      }
    }

    public enum Type {
      @SerializedName("bucket")
      BUCKET("bucket"),

      @SerializedName("finite")
      FINITE("finite"),

      @SerializedName("infinite")
      INFINITE("infinite");

      private final String value;

      Type(String value) {
        this.value = value;
      }
    }

    public enum Value {
      @SerializedName("in_stock")
      IN_STOCK("in_stock"),

      @SerializedName("limited")
      LIMITED("limited"),

      @SerializedName("out_of_stock")
      OUT_OF_STOCK("out_of_stock");

      private final String value;

      Value(String value) {
        this.value = value;
      }
    }
  }

  public static class PackageDimensions {
    @SerializedName("height")
    BigDecimal height;

    @SerializedName("length")
    BigDecimal length;

    @SerializedName("weight")
    BigDecimal weight;

    @SerializedName("width")
    BigDecimal width;

    private PackageDimensions(
        BigDecimal height, BigDecimal length, BigDecimal weight, BigDecimal width) {
      this.height = height;
      this.length = length;
      this.weight = weight;
      this.width = width;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SkuUpdateParams.PackageDimensions.Builder();
    }

    public static class Builder {
      private BigDecimal height;

      private BigDecimal length;

      private BigDecimal weight;

      private BigDecimal width;

      public PackageDimensions build() {
        return new PackageDimensions(height, length, weight, width);
      }

      public Builder setHeight(BigDecimal height) {
        this.height = height;
        return this;
      }

      public Builder setLength(BigDecimal length) {
        this.length = length;
        return this;
      }

      public Builder setWeight(BigDecimal weight) {
        this.weight = weight;
        return this;
      }

      public Builder setWidth(BigDecimal width) {
        this.width = width;
        return this;
      }
    }
  }
}
