// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class SourceRetrieveParams extends ApiParamRequest {
  @SerializedName("client_secret")
  String clientSecret;

  @SerializedName("expand")
  List<String> expand;

  private SourceRetrieveParams(String clientSecret, List<String> expand) {
    this.clientSecret = clientSecret;
    this.expand = expand;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.SourceRetrieveParams.Builder();
  }

  public static class Builder {
    private String clientSecret;

    private List<String> expand;

    public SourceRetrieveParams build() {
      return new SourceRetrieveParams(clientSecret, expand);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setClientSecret(String clientSecret) {
      this.clientSecret = clientSecret;
      return this;
    }
  }
}
