// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;

public class SubscriptionItemDeleteParams extends ApiParamRequest {
  @SerializedName("clear_usage")
  Boolean clearUsage;

  @SerializedName("prorate")
  Boolean prorate;

  @SerializedName("proration_date")
  Long prorationDate;

  private SubscriptionItemDeleteParams(Boolean clearUsage, Boolean prorate, Long prorationDate) {
    this.clearUsage = clearUsage;
    this.prorate = prorate;
    this.prorationDate = prorationDate;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.SubscriptionItemDeleteParams.Builder();
  }

  public static class Builder {
    private Boolean clearUsage;

    private Boolean prorate;

    private Long prorationDate;

    public SubscriptionItemDeleteParams build() {
      return new SubscriptionItemDeleteParams(clearUsage, prorate, prorationDate);
    }

    public Builder setClearUsage(Boolean clearUsage) {
      this.clearUsage = clearUsage;
      return this;
    }

    public Builder setProrate(Boolean prorate) {
      this.prorate = prorate;
      return this;
    }

    public Builder setProrationDate(Long prorationDate) {
      this.prorationDate = prorationDate;
      return this;
    }
  }
}
