// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class SubscriptionListParams extends ApiParamRequest {
  @SerializedName("billing")
  Billing billing;

  @SerializedName("created")
  Object created;

  @SerializedName("customer")
  String customer;

  @SerializedName("ending_before")
  String endingBefore;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("limit")
  Long limit;

  @SerializedName("plan")
  String plan;

  @SerializedName("starting_after")
  String startingAfter;

  @SerializedName("status")
  Status status;

  private SubscriptionListParams(
      Billing billing,
      Object created,
      String customer,
      String endingBefore,
      List<String> expand,
      Long limit,
      String plan,
      String startingAfter,
      Status status) {
    this.billing = billing;
    this.created = created;
    this.customer = customer;
    this.endingBefore = endingBefore;
    this.expand = expand;
    this.limit = limit;
    this.plan = plan;
    this.startingAfter = startingAfter;
    this.status = status;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.SubscriptionListParams.Builder();
  }

  public static class Builder {
    private Billing billing;

    private Object created;

    private String customer;

    private String endingBefore;

    private List<String> expand;

    private Long limit;

    private String plan;

    private String startingAfter;

    private Status status;

    public SubscriptionListParams build() {
      return new SubscriptionListParams(
          billing, created, customer, endingBefore, expand, limit, plan, startingAfter, status);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setBilling(Billing billing) {
      this.billing = billing;
      return this;
    }

    public Builder setCreated(Created.Builder created) {
      this.created = created.build();
      return this;
    }

    public Builder setCreated(Long created) {
      this.created = created;
      return this;
    }

    public Builder setCustomer(String customer) {
      this.customer = customer;
      return this;
    }

    public Builder setEndingBefore(String endingBefore) {
      this.endingBefore = endingBefore;
      return this;
    }

    public Builder setLimit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder setPlan(String plan) {
      this.plan = plan;
      return this;
    }

    public Builder setStartingAfter(String startingAfter) {
      this.startingAfter = startingAfter;
      return this;
    }

    public Builder setStatus(Status status) {
      this.status = status;
      return this;
    }
  }

  public static class Created {
    @SerializedName("gt")
    Long gt;

    @SerializedName("gte")
    Long gte;

    @SerializedName("lt")
    Long lt;

    @SerializedName("lte")
    Long lte;

    private Created(Long gt, Long gte, Long lt, Long lte) {
      this.gt = gt;
      this.gte = gte;
      this.lt = lt;
      this.lte = lte;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SubscriptionListParams.Created.Builder();
    }

    public static class Builder {
      private Long gt;

      private Long gte;

      private Long lt;

      private Long lte;

      public Created build() {
        return new Created(gt, gte, lt, lte);
      }

      public Builder setGt(Long gt) {
        this.gt = gt;
        return this;
      }

      public Builder setGte(Long gte) {
        this.gte = gte;
        return this;
      }

      public Builder setLt(Long lt) {
        this.lt = lt;
        return this;
      }

      public Builder setLte(Long lte) {
        this.lte = lte;
        return this;
      }
    }
  }

  public enum Billing {
    @SerializedName("charge_automatically")
    CHARGE_AUTOMATICALLY("charge_automatically"),

    @SerializedName("send_invoice")
    SEND_INVOICE("send_invoice");

    private final String value;

    Billing(String value) {
      this.value = value;
    }
  }

  public enum Status {
    @SerializedName("active")
    ACTIVE("active"),

    @SerializedName("all")
    ALL("all"),

    @SerializedName("canceled")
    CANCELED("canceled"),

    @SerializedName("ended")
    ENDED("ended"),

    @SerializedName("incomplete")
    INCOMPLETE("incomplete"),

    @SerializedName("incomplete_expired")
    INCOMPLETE_EXPIRED("incomplete_expired"),

    @SerializedName("past_due")
    PAST_DUE("past_due"),

    @SerializedName("trialing")
    TRIALING("trialing"),

    @SerializedName("unpaid")
    UNPAID("unpaid");

    private final String value;

    Status(String value) {
      this.value = value;
    }
  }
}
