// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class SubscriptionScheduleListParams extends ApiParamRequest {
  @SerializedName("canceled_at")
  Object canceledAt;

  @SerializedName("completed_at")
  Object completedAt;

  @SerializedName("created")
  Object created;

  @SerializedName("customer")
  String customer;

  @SerializedName("ending_before")
  String endingBefore;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("limit")
  Long limit;

  @SerializedName("released_at")
  Object releasedAt;

  @SerializedName("scheduled")
  Boolean scheduled;

  @SerializedName("starting_after")
  String startingAfter;

  private SubscriptionScheduleListParams(
      Object canceledAt,
      Object completedAt,
      Object created,
      String customer,
      String endingBefore,
      List<String> expand,
      Long limit,
      Object releasedAt,
      Boolean scheduled,
      String startingAfter) {
    this.canceledAt = canceledAt;
    this.completedAt = completedAt;
    this.created = created;
    this.customer = customer;
    this.endingBefore = endingBefore;
    this.expand = expand;
    this.limit = limit;
    this.releasedAt = releasedAt;
    this.scheduled = scheduled;
    this.startingAfter = startingAfter;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.SubscriptionScheduleListParams.Builder();
  }

  public static class Builder {
    private Object canceledAt;

    private Object completedAt;

    private Object created;

    private String customer;

    private String endingBefore;

    private List<String> expand;

    private Long limit;

    private Object releasedAt;

    private Boolean scheduled;

    private String startingAfter;

    public SubscriptionScheduleListParams build() {
      return new SubscriptionScheduleListParams(
          canceledAt,
          completedAt,
          created,
          customer,
          endingBefore,
          expand,
          limit,
          releasedAt,
          scheduled,
          startingAfter);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setCanceledAt(Long canceledAt) {
      this.canceledAt = canceledAt;
      return this;
    }

    public Builder setCanceledAt(CanceledAt.Builder canceledAt) {
      this.canceledAt = canceledAt.build();
      return this;
    }

    public Builder setCompletedAt(Long completedAt) {
      this.completedAt = completedAt;
      return this;
    }

    public Builder setCompletedAt(CompletedAt.Builder completedAt) {
      this.completedAt = completedAt.build();
      return this;
    }

    public Builder setCreated(Long created) {
      this.created = created;
      return this;
    }

    public Builder setCreated(Created.Builder created) {
      this.created = created.build();
      return this;
    }

    public Builder setCustomer(String customer) {
      this.customer = customer;
      return this;
    }

    public Builder setEndingBefore(String endingBefore) {
      this.endingBefore = endingBefore;
      return this;
    }

    public Builder setLimit(Long limit) {
      this.limit = limit;
      return this;
    }

    public Builder setReleasedAt(Long releasedAt) {
      this.releasedAt = releasedAt;
      return this;
    }

    public Builder setReleasedAt(ReleasedAt.Builder releasedAt) {
      this.releasedAt = releasedAt.build();
      return this;
    }

    public Builder setScheduled(Boolean scheduled) {
      this.scheduled = scheduled;
      return this;
    }

    public Builder setStartingAfter(String startingAfter) {
      this.startingAfter = startingAfter;
      return this;
    }
  }

  public static class CanceledAt {
    @SerializedName("gt")
    Long gt;

    @SerializedName("gte")
    Long gte;

    @SerializedName("lt")
    Long lt;

    @SerializedName("lte")
    Long lte;

    private CanceledAt(Long gt, Long gte, Long lt, Long lte) {
      this.gt = gt;
      this.gte = gte;
      this.lt = lt;
      this.lte = lte;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SubscriptionScheduleListParams.CanceledAt.Builder();
    }

    public static class Builder {
      private Long gt;

      private Long gte;

      private Long lt;

      private Long lte;

      public CanceledAt build() {
        return new CanceledAt(gt, gte, lt, lte);
      }

      public Builder setGt(Long gt) {
        this.gt = gt;
        return this;
      }

      public Builder setGte(Long gte) {
        this.gte = gte;
        return this;
      }

      public Builder setLt(Long lt) {
        this.lt = lt;
        return this;
      }

      public Builder setLte(Long lte) {
        this.lte = lte;
        return this;
      }
    }
  }

  public static class CompletedAt {
    @SerializedName("gt")
    Long gt;

    @SerializedName("gte")
    Long gte;

    @SerializedName("lt")
    Long lt;

    @SerializedName("lte")
    Long lte;

    private CompletedAt(Long gt, Long gte, Long lt, Long lte) {
      this.gt = gt;
      this.gte = gte;
      this.lt = lt;
      this.lte = lte;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SubscriptionScheduleListParams.CompletedAt.Builder();
    }

    public static class Builder {
      private Long gt;

      private Long gte;

      private Long lt;

      private Long lte;

      public CompletedAt build() {
        return new CompletedAt(gt, gte, lt, lte);
      }

      public Builder setGt(Long gt) {
        this.gt = gt;
        return this;
      }

      public Builder setGte(Long gte) {
        this.gte = gte;
        return this;
      }

      public Builder setLt(Long lt) {
        this.lt = lt;
        return this;
      }

      public Builder setLte(Long lte) {
        this.lte = lte;
        return this;
      }
    }
  }

  public static class Created {
    @SerializedName("gt")
    Long gt;

    @SerializedName("gte")
    Long gte;

    @SerializedName("lt")
    Long lt;

    @SerializedName("lte")
    Long lte;

    private Created(Long gt, Long gte, Long lt, Long lte) {
      this.gt = gt;
      this.gte = gte;
      this.lt = lt;
      this.lte = lte;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SubscriptionScheduleListParams.Created.Builder();
    }

    public static class Builder {
      private Long gt;

      private Long gte;

      private Long lt;

      private Long lte;

      public Created build() {
        return new Created(gt, gte, lt, lte);
      }

      public Builder setGt(Long gt) {
        this.gt = gt;
        return this;
      }

      public Builder setGte(Long gte) {
        this.gte = gte;
        return this;
      }

      public Builder setLt(Long lt) {
        this.lt = lt;
        return this;
      }

      public Builder setLte(Long lte) {
        this.lte = lte;
        return this;
      }
    }
  }

  public static class ReleasedAt {
    @SerializedName("gt")
    Long gt;

    @SerializedName("gte")
    Long gte;

    @SerializedName("lt")
    Long lt;

    @SerializedName("lte")
    Long lte;

    private ReleasedAt(Long gt, Long gte, Long lt, Long lte) {
      this.gt = gt;
      this.gte = gte;
      this.lt = lt;
      this.lte = lte;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.SubscriptionScheduleListParams.ReleasedAt.Builder();
    }

    public static class Builder {
      private Long gt;

      private Long gte;

      private Long lt;

      private Long lte;

      public ReleasedAt build() {
        return new ReleasedAt(gt, gte, lt, lte);
      }

      public Builder setGt(Long gt) {
        this.gt = gt;
        return this;
      }

      public Builder setGte(Long gte) {
        this.gte = gte;
        return this;
      }

      public Builder setLt(Long lt) {
        this.lt = lt;
        return this;
      }

      public Builder setLte(Long lte) {
        this.lte = lte;
        return this;
      }
    }
  }
}
