// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class ThreeDSecureCreateParams extends ApiParamRequest {
  @SerializedName("amount")
  Long amount;

  @SerializedName("card")
  String card;

  @SerializedName("currency")
  String currency;

  @SerializedName("customer")
  String customer;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("return_url")
  String returnUrl;

  private ThreeDSecureCreateParams(
      Long amount,
      String card,
      String currency,
      String customer,
      List<String> expand,
      String returnUrl) {
    this.amount = amount;
    this.card = card;
    this.currency = currency;
    this.customer = customer;
    this.expand = expand;
    this.returnUrl = returnUrl;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.ThreeDSecureCreateParams.Builder();
  }

  public static class Builder {
    private Long amount;

    private String card;

    private String currency;

    private String customer;

    private List<String> expand;

    private String returnUrl;

    public ThreeDSecureCreateParams build() {
      return new ThreeDSecureCreateParams(amount, card, currency, customer, expand, returnUrl);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setAmount(Long amount) {
      this.amount = amount;
      return this;
    }

    public Builder setCard(String card) {
      this.card = card;
      return this;
    }

    public Builder setCurrency(String currency) {
      this.currency = currency;
      return this;
    }

    public Builder setCustomer(String customer) {
      this.customer = customer;
      return this;
    }

    public Builder setReturnUrl(String returnUrl) {
      this.returnUrl = returnUrl;
      return this;
    }
  }
}
