// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TopupCreateParams extends ApiParamRequest {
  @SerializedName("amount")
  Long amount;

  @SerializedName("currency")
  String currency;

  @SerializedName("description")
  String description;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("metadata")
  Map<String, String> metadata;

  @SerializedName("source")
  String source;

  @SerializedName("statement_descriptor")
  String statementDescriptor;

  @SerializedName("transfer_group")
  String transferGroup;

  private TopupCreateParams(
      Long amount,
      String currency,
      String description,
      List<String> expand,
      Map<String, String> metadata,
      String source,
      String statementDescriptor,
      String transferGroup) {
    this.amount = amount;
    this.currency = currency;
    this.description = description;
    this.expand = expand;
    this.metadata = metadata;
    this.source = source;
    this.statementDescriptor = statementDescriptor;
    this.transferGroup = transferGroup;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.TopupCreateParams.Builder();
  }

  public static class Builder {
    private Long amount;

    private String currency;

    private String description;

    private List<String> expand;

    private Map<String, String> metadata;

    private String source;

    private String statementDescriptor;

    private String transferGroup;

    public TopupCreateParams build() {
      return new TopupCreateParams(
          amount,
          currency,
          description,
          expand,
          metadata,
          source,
          statementDescriptor,
          transferGroup);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder putMetadata(String key, String value) {
      if (this.metadata == null) {
        this.metadata = new HashMap<>();
      }
      this.metadata.put(key, value);
      return this;
    }

    public Builder setAmount(Long amount) {
      this.amount = amount;
      return this;
    }

    public Builder setCurrency(String currency) {
      this.currency = currency;
      return this;
    }

    public Builder setDescription(String description) {
      this.description = description;
      return this;
    }

    public Builder setSource(String source) {
      this.source = source;
      return this;
    }

    public Builder setStatementDescriptor(String statementDescriptor) {
      this.statementDescriptor = statementDescriptor;
      return this;
    }

    public Builder setTransferGroup(String transferGroup) {
      this.transferGroup = transferGroup;
      return this;
    }
  }
}
