// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.terminal;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class LocationCreateParams extends ApiParamRequest {
  @SerializedName("address")
  Address address;

  @SerializedName("display_name")
  String displayName;

  @SerializedName("expand")
  List<String> expand;

  @SerializedName("operator_account")
  String operatorAccount;

  private LocationCreateParams(
      Address address, String displayName, List<String> expand, String operatorAccount) {
    this.address = address;
    this.displayName = displayName;
    this.expand = expand;
    this.operatorAccount = operatorAccount;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.terminal.LocationCreateParams.Builder();
  }

  public static class Builder {
    private Address address;

    private String displayName;

    private List<String> expand;

    private String operatorAccount;

    public LocationCreateParams build() {
      return new LocationCreateParams(address, displayName, expand, operatorAccount);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setAddress(Address.Builder address) {
      this.address = address.build();
      return this;
    }

    public Builder setDisplayName(String displayName) {
      this.displayName = displayName;
      return this;
    }

    public Builder setOperatorAccount(String operatorAccount) {
      this.operatorAccount = operatorAccount;
      return this;
    }
  }

  public static class Address {
    @SerializedName("city")
    String city;

    @SerializedName("country")
    String country;

    @SerializedName("line1")
    String line1;

    @SerializedName("line2")
    String line2;

    @SerializedName("postal_code")
    String postalCode;

    @SerializedName("state")
    String state;

    private Address(
        String city, String country, String line1, String line2, String postalCode, String state) {
      this.city = city;
      this.country = country;
      this.line1 = line1;
      this.line2 = line2;
      this.postalCode = postalCode;
      this.state = state;
    }

    public static Builder newBuilder() {
      return new com.stripe.param.terminal.LocationCreateParams.Address.Builder();
    }

    public static class Builder {
      private String city;

      private String country;

      private String line1;

      private String line2;

      private String postalCode;

      private String state;

      public Address build() {
        return new Address(city, country, line1, line2, postalCode, state);
      }

      public Builder setCity(String city) {
        this.city = city;
        return this;
      }

      public Builder setCountry(String country) {
        this.country = country;
        return this;
      }

      public Builder setLine1(String line1) {
        this.line1 = line1;
        return this;
      }

      public Builder setLine2(String line2) {
        this.line2 = line2;
        return this;
      }

      public Builder setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
      }

      public Builder setState(String state) {
        this.state = state;
        return this;
      }
    }
  }
}
