// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.terminal;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class LocationRetrieveParams extends ApiParamRequest {
  @SerializedName("expand")
  List<String> expand;

  @SerializedName("operator_account")
  String operatorAccount;

  private LocationRetrieveParams(List<String> expand, String operatorAccount) {
    this.expand = expand;
    this.operatorAccount = operatorAccount;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.terminal.LocationRetrieveParams.Builder();
  }

  public static class Builder {
    private List<String> expand;

    private String operatorAccount;

    public LocationRetrieveParams build() {
      return new LocationRetrieveParams(expand, operatorAccount);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setOperatorAccount(String operatorAccount) {
      this.operatorAccount = operatorAccount;
      return this;
    }
  }
}
