// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.terminal;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiParamRequest;
import java.util.ArrayList;
import java.util.List;

public class ReaderUpdateParams extends ApiParamRequest {
  @SerializedName("expand")
  List<String> expand;

  @SerializedName("label")
  String label;

  @SerializedName("operator_account")
  String operatorAccount;

  private ReaderUpdateParams(List<String> expand, String label, String operatorAccount) {
    this.expand = expand;
    this.label = label;
    this.operatorAccount = operatorAccount;
  }

  public static Builder newBuilder() {
    return new com.stripe.param.terminal.ReaderUpdateParams.Builder();
  }

  public static class Builder {
    private List<String> expand;

    private String label;

    private String operatorAccount;

    public ReaderUpdateParams build() {
      return new ReaderUpdateParams(expand, label, operatorAccount);
    }

    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    public Builder setLabel(String label) {
      this.label = label;
      return this;
    }

    public Builder setOperatorAccount(String operatorAccount) {
      this.operatorAccount = operatorAccount;
      return this;
    }
  }
}
